### User Creation
# @name create_user
POST http://localhost:8000/api/auth/create
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe4@example.com",
    "password": "securepassword123!",
    "password_confirmation": "securepassword123!"
}

###

### Authentication
# @name auth
POST http://localhost:8000/api/auth
Content-Type: application/json

{
  "email": "johndoe4@example.com",
  "password": "securepassword123!"
}

### Load Token
@token = {{auth.response.body.data.access_token}}

###

## TodoLists
### Get All TodoLists
GET http://localhost:8000/api/todo
Authorization: Bearer {{token}}

###

### Create a New TodoList
# @name createTodo
POST http://localhost:8000/api/todo
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Tudo Novo12"
}

###

### Load TodoList Id
@todoId = {{createTodo.response.body.data.id}}
@userId = {{createTodo.response.body.data.user_id}}
###

### Get a Specific TodoList 
GET http://localhost:8000/api/todo/{{todoId}}
Authorization: Bearer {{token}}
###

### Update a Specific TodoList
PUT http://localhost:8000/api/todo/{{todoId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "TudoNovo1"
}

###

### Delete a Specific TodoList
DELETE http://localhost:8000/api/todo/{{todoId}}
Authorization: Bearer {{token}}

###

### Get All Tasks from a Specific TodoList
GET http://localhost:8000/api/todo/{{todoId}}/tasks
Authorization: Bearer {{token}}

###

## Tasks
### Create a New Task in a Specific TodoList
# @name createTask
POST http://localhost:8000/api/todo/{{todoId}}/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "My First Task",
    "description": "This is the description of my first task."
}

###

@taskId = {{createTask.response.body.data.id}}

### Get a Specific Task from a Specific TodoList
GET http://localhost:8000/api/todo/{{todoId}}/tasks/{{taskId}}
Authorization: Bearer {{token}}

###

### Update a Specific Task in a Specific TodoList
PUT http://localhost:8000/api/todo/{{todoId}}/tasks/{{taskId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Updated Task Title",
    "description": "This is the updated description of my first task.",
    "completed": true
}

###

### Delete a Specific Task from a Specific TodoList
DELETE http://localhost:8000/api/todo/{{todoId}}/tasks/{{taskId}}
Authorization: Bearer {{token}}
###
